### ISSUE TITLE
Tugas1

### ISSUE THREAD

**Issue by sainsdataikopin** [sevinurafni/AB1203#1]
Format Pengumpulan:
Nama - NRP
upload file dengan diberi nama NamaMahasiswa-NRP.pdf

**Comment by mchydhamlna** [comment]
Moch Yudha Maulana - 2C1230001
https://github.com/mchydhamlna/Tugas_1_AB1203/blob/main/Tugas_1.md

**Comment by alyanrni25** [comment]
Alya Nuraeni - 2C1230011
[AlyaNuraeni-2C1230011.pdf](https://github.com/sevinurafni/AB1203/files/14403984/AlyaNuraeni-2C1230011.pdf)

**Comment by maudiiiy** [comment]
Maudina Rachmawati - 2C1230010
[MaudinaRachmawati_2C1230010.pdf](https://github.com/sevinurafni/AB1203/files/14468977/MaudinaRachmawati_2C1230010.pdf)

**Comment by fenitasari** [comment]
Fenita Sari- 2C123002
[fenitasari_2C123002 (2).pdf](https://github.com/sevinurafni/AB1203/files/14468983/fenitasari_2C123002.2.pdf)

**Comment by fanitaanggraeni** [comment]
Fanita Anggraeni- 2C1230003
[fanita anggraeni (2C1230003).pdf](https://github.com/sevinurafni/AB1203/files/14469508/fanita.anggraeni.2C1230003.pdf)

**Comment by kayla0204** [comment]
Kayla Ayu - 2C1230008
[Kayla Ayu-2C1230008.pdf](https://github.com/sevinurafni/AB1203/files/14471332/Kayla.Ayu-2C1230008.pdf)

**Comment by RepaNurulAida** [comment]
Repa Nurul Aida - 2C1230009
Repa Nurul Aida-2C1230009 (1).pdf

**Comment by RepaNurulAida** [comment]
Repa Nurul Aida-2C1230009
[Repa Nurul Aida-2C1230009 (1).pdf](https://github.com/sevinurafni/AB1203/files/14471343/Repa.Nurul.Aida-2C1230009.1.pdf)

**Comment by annisayustiani** [comment]
Annisa Yustiani-2C1230007
[Annisa Yustiani_2C1230007.pdf](https://github.com/sevinurafni/AB1203/files/14472245/Annisa.Yustiani_2C1230007.pdf)

**Comment by wiliagung22** [comment]
Wili Agung Saputra-2C1230013
[Wili Agung Saputra-2C1230013.pdf](https://github.com/sevinurafni/AB1203/files/14472266/Wili.Agung.Saputra-2C1230013.pdf)

**Comment by wiliagung22** [comment]
Wili Agung Saputra-2C1230013
[Wili Agung-2C1230013.pdf](https://github.com/sevinurafni/AB1203/files/14472274/Wili.Agung-2C1230013.pdf)

**Comment by DianaFriskaAulia** [comment]
Diana friska aulia -2C1230004
[Diana Friska Aulia -2C1230004.pdf](https://github.com/sevinurafni/AB1203/files/14472777/Diana.Friska.Aulia.-2C1230004.pdf)
