### ISSUE TITLE
Tugas2

### ISSUE THREAD

**Issue by sainsdataikopin** [sevinurafni/AB1203#3]
Format Pengumpulan:
Nama - NRP
upload file dengan diberi nama NamaMahasiswa-NRP.pdf

Deadline: 10 Maret 2024 23:59

**Comment by maudiiiy** [comment]
Maudiona Rachmawati - 2C1230010
[Uploading MaudinaRachmawati_2C1230010.pdf…]()

**Comment by annisayustiani** [comment]
Annisa Yustiani_2C1230007
[Uploading Annisa Yustiani_2C1230007.pdf…]()

**Comment by mchydhamlna** [comment]
Moch Yudha Maulana - 2C1230001
https://github.com/mchydhamlna/Tugas_AB1203/blob/main/Tugas_2.md

**Comment by fenitasari** [comment]
Fenita Sari - 2C123002
[fenitasari_2C123002 (P2).pdf](https://github.com/sevinurafni/AB1203/files/14481435/fenitasari_2C123002.P2.pdf)

**Comment by fanitaanggraeni** [comment]
Fanita Anggraeni - 2C1230003
[fanita tugas pertemuan ke 2.pdf](https://github.com/sevinurafni/AB1203/files/14484195/fanita.tugas.pertemuan.ke.2.pdf)

**Comment by maudiiiy** [comment]
Maudina Rachmawati - 2C1230010
[MaudinaRachmawati_2C1230010.pdf](https://github.com/sevinurafni/AB1203/files/14516931/MaudinaRachmawati_2C1230010.pdf)

**Comment by wiliagung22** [comment]
Annisa Yustiani-2C1230007
[Annisa Yustiani_2C1230007.pdf](https://github.com/sevinurafni/AB1203/files/14518895/Annisa.Yustiani_2C1230007.pdf)

**Comment by annisayustiani** [comment]
Annisa Yustiani-2C1230007
[Annisa Yustiani_2C1230007.pdf](https://github.com/sevinurafni/AB1203/files/14518943/Annisa.Yustiani_2C1230007.pdf)

**Comment by wiliagung22** [comment]
Wili Agung Saputra-2C1230013
[Wili Agung Saputra.pdf](https://github.com/sevinurafni/AB1203/files/14519069/Wili.Agung.Saputra.pdf)

**Comment by alyanrni25** [comment]
Alya Nuraeni - 2C1230011
[Alya Nuraeni - 2C1230011.pdf](https://github.com/sevinurafni/AB1203/files/14545286/Alya.Nuraeni.-.2C1230011.pdf)

**Comment by RepaNurulAida** [comment]
Repa Nurul Aida-2C1230009
[Repa Nurul Aida-2C1230009.pdf](https://github.com/sevinurafni/AB1203/files/14546525/Repa.Nurul.Aida-2C1230009.pdf)

**Comment by kayla0204** [comment]
Kayla Ayu - 2C1230008
[Tugas2_KaylaAyu_2C1230008.pdf](https://github.com/sevinurafni/AB1203/files/14548169/Tugas2_KaylaAyu_2C1230008.pdf)

**Comment by DianaFriskaAulia** [comment]
Diana Friska Aulia - 2C1230004
[Diana Friska Aulia_2C1230004.pdf](https://github.com/sevinurafni/AB1203/files/14549884/Diana.Friska.Aulia_2C1230004.pdf)

**Comment by euisjulianingsih** [comment]
Euis Julia Ningsih 2C1230006
[Euis julia ningsih_2C1230006.pdf](https://github.com/sevinurafni/AB1203/files/14553355/Euis.julia.ningsih_2C1230006.pdf)

**Comment by sevinurafni** [comment]
> Maudiona Rachmawati - 2C1230010 Uploading MaudinaRachmawati_2C1230010.pdf…

saya tidak bisa mengecek tugas Anda, @maudiiiy.

**Comment by sevinurafni** [comment]
> Annisa Yustiani_2C1230007 Uploading Annisa Yustiani_2C1230007.pdf…

saya tidak bisa mengecek tugas Anda, @annisayustiani.
