### ISSUE TITLE
Coding di Lab

### ISSUE THREAD

**Issue by sainsdataikopin** [sevinurafni/AB1203#5]
Nama - NRP - program

upload juga capture hasil running dari program

**Comment by kayla0204** [comment]
Kayla Ayu - 2C1230008 - Menghitung Luas&Keliling Persegi Panjang
https://github.com/kayla0204/TugasProgram/tree/main/MenghitungLuas%26KelilingPersegiPanjang

**Comment by mchydhamlna** [comment]
Moch Yudha Maulana - 2C1230001
https://github.com/mchydhamlna/Tugas_AB1203/blob/main/CodingLab.md

**Comment by maudiiiy** [comment]
Maudina Rachmawati - 2C1230010
https://github.com/maudiiiy/TugasProgramLAb/commit/11b5f3e44b275c5293e92ea772dd267294792378

**Comment by annisayustiani** [comment]
Annisa Yustiani - 2C1230007
https://github.com/annisayustiani/TugasPemograman/tree/main/AnnisaYustiani_Agribisnis

**Comment by RepaNurulAida** [comment]
Repa Nurul Aida - 2C1230009
https://github.com/RepaNurulAida/TugasProgram/tree/main/menghitungluas%26kelilingpersegipanjang

**Comment by maudiiiy** [comment]
Maudina Rachmawati - 2C1230010
https://github.com/maudiiiy/TugasProgramLAb/tree/main/prakteklab

**Comment by alyanrni25** [comment]
Alya Nuraeni - 2C1230011
https://github.com/alyanrni25/Tugas_1_AB1203/blob/main/coding_lab.md

**Comment by fenitasari** [comment]
Fenita Sari - 2C1230002
![Screenshot (3)](https://github.com/sevinurafni/AB1203/assets/156888132/10952b07-49b7-49af-b5d3-c86f879bb490)

**Comment by fenitasari** [comment]
Fenita Sari-2C1230002
https://github.com/fenitasari/fenita/tree/main/praktikumlab

**Comment by DianaFriskaAulia** [comment]
Diana Friska Aulia -2C1230004
https://github.com/DianaFriskaAulia/TugasAlpro/blob/main/codinglab.md

**Comment by wiliagung22** [comment]
Wili Agung Saputra - 2C1230013
https://github.com/wiliagung22/TugasPemograman/tree/main/Wili_Agribisnis

**Comment by euisjulianingsih** [comment]
euis julia ningsih 2C1230006 
https://github.com/euisjulianingsih/TugasAlpro/blob/main/codinglab.md

**Comment by fanitaanggraeni** [comment]
fanita anggraeni 2C1230003
https://github.com/fanitaanggraeni/tugaslab/tree/main/tugaslab
