### ISSUE TITLE
Coding di Lab

### ISSUE THREAD

**Issue by sainsdataikopin** [sevinurafni/AB1203#7]
Tampilkan nilai berikut dengan looping (perulangan)
(2, 5, 3, 2, 4)

**Comment by maudiiiy** [comment]
Maudina Rachmawati - 2C1230010
https://github.com/maudiiiy/TugasProgramLAb/tree/main/Tugas%20matriks

**Comment by kayla0204** [comment]
Kayla ayu - 2C1230008
https://github.com/kayla0204/TugasProgram/blob/main/TugasLab2.md

**Comment by RepaNurulAida** [comment]
Repa Nurul Aida - 2C1230009
https://github.com/RepaNurulAida/TugasAlpro/blob/main/TugasLab2.md

**Comment by DianaFriskaAulia** [comment]
Diana friska aulia - 2C1230004
https://github.com/DianaFriskaAulia/TugasAlpro/blob/main/tugaslab.md

**Comment by maudiiiy** [comment]
Maudina Rachmawati - 2C1230010
https://github.com/maudiiiy/TugasPraktikumLab/tree/main/Tugas%20matriks

**Comment by annisayustiani** [comment]
Annisa Yustiani-2C1230007
https://github.com/annisayustiani/TugasPemograman/tree/main/Annisa%20Yustiani_Matriks_Agribisnis

**Comment by alyanrni25** [comment]
Alya Nuraeni-2C1230011
https://github.com/alyanrni25/TugasAlpro/blob/main/array.md

**Comment by fenitasari** [comment]
Fenita Sari-2C1230002
https://github.com/fenitasari/fenita/blob/main/README.md

**Comment by euisjulianingsih** [comment]
euis julia ningsih 2C1230006 
https://github.com/euisjulianingsih/TugasAlpro/blob/main/tugaslab.md

**Comment by fanitaanggraeni** [comment]
Fanita anggraeni - 2C1230003
https://github.com/fanitaanggraeni/fanita/blob/main/Untitled-1.cpp

**Comment by fenitasari** [comment]
Fenita Sari - 2C1230002
https://github.com/fenitasari/fenita/blob/main/fenitatgslab2.md

**Comment by wiliagung22** [comment]
Wili Agung Saputra - 2C1230013
https://github.com/wiliagung22/TugasPemograman/tree/main/wili%20matriks

**Comment by muhamadhilmi06** [comment]
![Screenshot (4)](https://github.com/sevinurafni/AB1203/assets/156994459/6a728917-28a9-43cd-90ed-b528e7e8dc65)
Muhamad Hilmi -2C1230005

**Comment by mchydhamlna** [comment]
Moch Yudha Maulana - 2C1230001
https://github.com/mchydhamlna/Tugas_AB1203/blob/main/CodingLab2.md
