### ISSUE TITLE
Qizz

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/AB1203#9]
[Quizz.md](https://github.com/sevinurafni/AB1203/files/15055677/Quizz.md)

Nama - NRP
Deadline: 22 April 2024, 9:15
Dikumpulkan dalam bentuk PDF untuk soal nomor 1 disertakan pula capture hasil running nya.

**Comment by mchydhamlna** [comment]
Moch Yudha Maulana - 2C1230001
[Quizz.pdf](https://github.com/sevinurafni/AB1203/files/15056369/Quizz.pdf)

**Comment by fanitaanggraeni** [comment]
Fanita anggraeni-2C1230003
[Uploading quiz fanita pemprograman22.pdf…]()

**Comment by kayla0204** [comment]
Kayla Ayu - 2C1230008
[KaylaAyu_kuis.pdf](https://github.com/sevinurafni/AB1203/files/15056412/KaylaAyu_kuis.pdf)

**Comment by fanitaanggraeni** [comment]
Fanita anggraeni-2C1230003
[quiz fanita pemprograman22.pdf](https://github.com/sevinurafni/AB1203/files/15056409/quiz.fanita.pemprograman22.pdf)

**Comment by RepaNurulAida** [comment]
Repa Nurul Aida-2C1230009
[REPA NURUL AIDA-2C1230009.pdf](https://github.com/sevinurafni/AB1203/files/15056423/REPA.NURUL.AIDA-2C1230009.pdf)

**Comment by DianaFriskaAulia** [comment]
diana friska aulia -2C1230004
[diana friska aulia 2C1230004.pdf](https://github.com/sevinurafni/AB1203/files/15056426/diana.friska.aulia.2C1230004.pdf)

**Comment by fenitasari** [comment]
Fenita Sari - 2C1230002
[Uploading fenita Quiz.pdf…]()

**Comment by euisjulianingsih** [comment]
euis julia ningsih- 2C1230006
[euis julia ningsih_2C1230006_agribisnis.pdf](https://github.com/sevinurafni/AB1203/files/15056440/euis.julia.ningsih_2C1230006_agribisnis.pdf)

**Comment by fenitasari** [comment]
fenita sari -2C1230002
[fenita Quiz.pdf](https://github.com/sevinurafni/AB1203/files/15056443/fenita.Quiz.pdf)

**Comment by annisayustiani** [comment]
Annisa Yustiani-2C1230007
[Annisa Yustiani-2C1230007.pdf](https://github.com/sevinurafni/AB1203/files/15056454/Annisa.Yustiani-2C1230007.pdf)

**Comment by maudiiiy** [comment]
maudina rachmawati - 2C1230010
[Uploading Maudina Quiz.pdf…]()

**Comment by maudiiiy** [comment]
maudina rachmawati - 2C1230010
[Maudina Quiz.pdf](https://github.com/sevinurafni/AB1203/files/15056462/Maudina.Quiz.pdf)

**Comment by alyanrni25** [comment]
Alya Nuraeni - 2C1230011
[alya.pdf](https://github.com/sevinurafni/AB1203/files/15056471/alya.pdf)
